
CREATE DATABASE IF NOT EXISTS REGISTRADOR_FILMES_LIVROS;
USE REGISTRADOR_FILMES_LIVROS;

CREATE TABLE usuario (
  ID_usuario INT NOT NULL AUTO_INCREMENT,
  Usuario VARCHAR(100) NOT NULL,
  Nome VARCHAR(100) NOT NULL,
  E_mail VARCHAR(100) NOT NULL UNIQUE,
  Senha VARCHAR(255) NOT NULL,
  Tipo_usuario ENUM('usuario', 'administrador') NOT NULL DEFAULT 'usuario',
  PRIMARY KEY (ID_usuario)
);


CREATE TABLE livro (
  ID_Livro INT NOT NULL AUTO_INCREMENT,
  ISBN VARCHAR(20) NOT NULL,
  Titulo VARCHAR(150) NOT NULL,
  Autor VARCHAR(100) NOT NULL,
  Idioma VARCHAR(50) NOT NULL,
  Editora VARCHAR(100),
  N_Paginas INT,
  Capa VARCHAR(255),
  PRIMARY KEY (ID_Livro)
);

CREATE TABLE sugestaolivro (
  ID_Livro INT NOT NULL AUTO_INCREMENT,
  ISBN VARCHAR(20) NOT NULL,
  Titulo VARCHAR(150) NOT NULL,
  Autor VARCHAR(100) NOT NULL,
  Idioma VARCHAR(50) NOT NULL,
  Editora VARCHAR(100),
  N_Paginas INT,
  Capa VARCHAR(255),
  PRIMARY KEY (ID_Livro)
);

CREATE TABLE filme (
  ID_filme INT NOT NULL AUTO_INCREMENT,
  IMDb_ID VARCHAR(20) NOT NULL,
  Titulo VARCHAR(150) NOT NULL,
  Diretor VARCHAR(100) NOT NULL,
  Idioma_original VARCHAR(50) NOT NULL,
  Ano_de_lancamento INT,
  Poster VARCHAR(255),
  PRIMARY KEY (ID_filme)
);

CREATE TABLE sugestaofilme (
  ID_filme INT NOT NULL AUTO_INCREMENT,
  IMDb_ID VARCHAR(20) NOT NULL,
  Titulo VARCHAR(150) NOT NULL,
  Diretor VARCHAR(100) NOT NULL,
  Idioma_original VARCHAR(50) NOT NULL,
  Ano_de_lancamento INT,
  Poster VARCHAR(255),
  PRIMARY KEY (ID_filme)
);

CREATE TABLE lista (
  ID_lista INT NOT NULL AUTO_INCREMENT,
  ID_usuario INT NOT NULL,
  Nome_lista VARCHAR(100) NOT NULL,
  Descricao TEXT NULL,
  Data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_lista),
  FOREIGN KEY (ID_usuario) REFERENCES usuario(ID_usuario)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE lista_midia (
  ID_lista_midia INT NOT NULL AUTO_INCREMENT,
  ID_lista INT NOT NULL,
  ID_livro INT NULL,
  ID_filme INT NULL,
  Data_consumo DATE NULL,
  Avaliacao INT DEFAULT NULL,
  Resenha TEXT,
  PRIMARY KEY (ID_lista_midia),
  FOREIGN KEY (ID_lista) REFERENCES lista(ID_lista)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (ID_livro) REFERENCES livro(ID_Livro)
    ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (ID_filme) REFERENCES filme(ID_filme)
    ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT chk_avaliacao CHECK (Avaliacao BETWEEN 0 AND 5 OR Avaliacao IS NULL)
);

  